In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
indep=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dep=dataset['charges']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [12]:
from sklearn.ensemble import RandomForestRegressor

# Update the parameter grid
param_grid = {
    'n_estimators': [100, 200],
    'max_features': ['sqrt', 'log2'],  # Replace 'auto' with 'sqrt' or 'log2'
    'max_depth': [10, 20, None]
}

# Now, using GridSearchCV or similar
from sklearn.model_selection import GridSearchCV

# Assuming you have a RandomForestRegressor
model = RandomForestRegressor()

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'max_depth': [10, 20, None],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [100, 200]})

In [14]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)


print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8724771212347464

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001447,0.002296,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.001142,0.001801,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.114097,0.041265,0.000569,0.001137,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.792729,0.764656,0.802285,0.804436,0.729536,0.778729,0.028389,6
3,0.936852,0.032992,0.024909,0.006206,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.814594,0.764072,0.843285,0.832544,0.762379,0.803375,0.034044,1
4,0.105657,0.014837,0.004847,0.004085,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.755278,0.743973,0.800002,0.803289,0.746609,0.769830,0.026266,8
5,0.933906,0.051537,0.031325,0.006024,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.801262,0.765259,0.841851,0.826480,0.763835,0.799737,0.031524,3
6,0.000794,0.001587,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.000585,0.001170,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.239774,0.023691,0.005765,0.005048,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.766538,0.762046,0.831757,0.800098,0.735127,0.779113,0.033454,5
9,2.049087,0.128439,0.035144,0.007373,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.799471,0.774257,0.836737,0.825542,0.763304,0.799862,0.028325,2
10,0.225805,0.027733,0.010553,0.006067,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.773486,0.757581,0.817713,0.800414,0.729208,0.775680,0.031211,7
11,1.901140,0.042136,0.024118,0.007742,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.803172,0.767389,0.837798,0.819455,0.760213,0.797605,0.029783,4

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:5
BMI:50
Children:3
Sex Male 0 or 1:4
Smoker Yes 0 or 1:5

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[47014.6215221]